### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 4: invalid start byte

### ISSUE THREAD

**Issue by sifacaii** [chrisemunt/mg_python#1]
CACHE :  Version cache-2010.2.2
mg_python : Version 2.3.47
zmgsi :  Version: 4.0; Revision 16 (11 February 2021)

Error when calling mg.m_get(0, "^Sample.PersonD",1):
File "/home/DHCC/mg.py", line 12, in <module>
    name = mg.m_get(0, "^Sample.PersonD",1)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 4: invalid start byte

**Comment by chrisemunt** [comment]
Looking at this global reference I suspect this is a global underpinning the storage for a Cache class.  If so, the data will be in a proprietary format (a Cache $List actually).  This is presumably what Python doesn't like.  At this stage there is only very basic support for Cache classes in mg_python and it would be best at this time to wrap this functionality in COS functions and have m_python call these instead of directly interacting with persistent class data.

**Comment by sifacaii** [comment]
thank you!

**Comment by chrisemunt** [comment]
A quick follow-up to this: mg_python now has improved support for InterSystems Cache/IRIS objects.  Details in the release notes.
